### PR TITLE
better default (IMO)

### PR DESCRIPTION
**Pull request by nicolasburtey**
so there is no need for dirty state on dev. this is override in prod with helm.

### CODE REVIEW

**Comment by bodymindarts** [comment]
Needs to be overwritten https://github.com/GaloyMoney/charts/blob/main/charts/galoy/values.yaml (You're PR disabled it in the _dev_ settings where it should actually also be active).

**Review by bodymindarts — APPROVED** [review]

**Comment by dolcalmi** [comment]
please dont forget to resolve writeSDLFile open handle if this is set to true by default.

**Comment by nicolasburtey** [comment]
@dolcalmi not sure to completely understand your point? do you wan to make a commit on my PR if there's something to fix?

**Comment by samerbuna** [comment]
> please dont forget to resolve writeSDLFile open handle if this is set to true by default. I fixed it here
> 
> https://github.com/GaloyMoney/galoy/blob/2d3a3452d083927b0876161017c03d1ab2965ab7/src/graphql/admin/index.ts#L16
> 
> but after rebase will not be validated when server runs from tests

Maybe we can mock that value in jest?

**Comment by dolcalmi** [comment]
> @dolcalmi not sure to completely understand your point? do you wan to make a commit on my PR if there's something to fix?

I dont know if this will be approved or not, just letting you know that this will create an open handle in tests (I had fixed it in another PR)

**Comment by nicolasburtey** [comment]
@dolcalmi can you approve this PR if this is good on your end? I'm not sure what is the status of the other PR you are referring to

**Review by dolcalmi — APPROVED** [review]
please dont forget update prod

**Pull request merged**
