### PR TITLE
Tests refactor - 1st stage

### PR DESCRIPTION
**Pull request by dolcalmi**
Move tests and mocks to test folder. Includes:
  - path changes
  - module import fixes
  - jest mocks and config fixes
  - neither the package/make/ci commands nor logic has been changed

Refs:
- https://github.com/GaloyMoney/galoy/issues/282
- https://galoymoney-workspace.slack.com/archives/C025EMR24KB/p1625698461365500

### CODE REVIEW

**Review by bodymindarts — DISMISSED** [review]
I'm approving this because I think we should merge quickly with so many changes so as not to block further progress. Its an excellent 1st stage for cleaning up the tests. Thank you!

But I have some comments:
- We are trying to move to a clean commit history with consistent messages. Please `C`apitalize the first word in the message and avoid `merge main into ...` commits. We prefer rebases. [Here](https://github.com/GaloyMoney/galoy/blob/main/DEV.md#contributing) is a link to 2 articles regarding commit style.
- You have named the test files `*.spec.ts`. I wasn't aware of this naming convention and  wanted to know if this is common and if you want to use the same naming for the unit tests? @samerbuna is the police for consistent naming around here.... what is your take?

**Comment by dolcalmi** [comment]
spec.

> I'm approving this because I think we should merge quickly with so many changes so as not to block further progress. Its an excellent 1st stage for cleaning up the tests. Thank you!
> 
> But I have some comments:
> 
> * We are trying to move to a clean commit history with consistent messages. Please `C`apitalize the first word in the message and avoid `merge main into ...` commits. We prefer rebases. [Here](https://github.com/GaloyMoney/galoy/blob/main/DEV.md#contributing) is a link to 2 articles regarding commit style.
> * You have named the test files `*.spec.ts`. I wasn't aware of this naming convention and  wanted to know if this is common and if you want to use the same naming for the unit tests? @samerbuna is the police for consistent naming around here.... what is your take?

- Commits: apologies, I thought you consolidate commits for the PR
- spec.[js|ts] , test.[js|ts] are common naming conventions even large frameworks like nestjs use it (they us jest too). I prefer this way because is easier to filter helper classes for tests.

**Comment by samerbuna** [comment]
`spec.ts` and `test.ts` are both okay. We can go with `spec.ts`.

**Review by samerbuna — CHANGES_REQUESTED** [review]
It would be great to quickly rebase this according to @bodymindarts comments, and push force this PR (I can pair with you on this if you want)

**Comment by dolcalmi** [comment]
done

**Review by samerbuna — APPROVED** [review]

**Review by bodymindarts — APPROVED** [review]

**Pull request merged**
