### PR TITLE
Remove all trailing whitespaces and add missing newlines at EOF

### PR DESCRIPTION
**Pull request by samerbuna**
NO CODE CHANGE

### CODE REVIEW

**Comment by nicolasburtey** [comment]
may be relevant to add a doc a code policy with the trailing whitespaces and missing newlines altogether with this PR. and maybe other stuff like variable name convention.

I don't have any strong opinion on this. but there is currently not much consistency in this repo.

**Comment by bodymindarts** [comment]
I think removing all needles whitespace and other noise from the repo is a good idea but we should add a linter config in the process so that it will be auto-enforced in the future.

A project-wide enforced code style is a good thing to reduces the amount of non functionality-critical discussions. 
A 1 time cleanup however doesn't solve this.

Perhaps @samerbuna could add a https://palantir.github.io/tslint/ or something similar.

**Comment by bodymindarts** [comment]
Looks like there already is a [task](https://github.com/GaloyMoney/galoy/blob/main/package.json#L4) for this. Its just not being enforced or not configured.

**Comment by bodymindarts** [comment]
@samerbuna can you join our [public slack](https://join.slack.com/t/galoymoney-workspace/shared_invite/zt-rvnhsdb5-72AZCD_jzw6_Q05aCs0SgA) to discuss.

**Comment by samerbuna** [comment]
Closing this PR as it'll be part of a new PR that adopts typescript-eslint

**Pull request closed without merging**
