### PR TITLE
Add new `extendLock` method to Lock service

### PR DESCRIPTION
**Pull request by vindard**
## Description

This PR adds a new `extendLock` method to our Lock service to wrap the `lockExtendOrThrow` method in a safe way for our new code style.

### CODE REVIEW

**Review by samerbuna — APPROVED** [review]

**Review by samerbuna — CHANGES_REQUESTED** [review]
Needs a rebase

**Review by samerbuna — APPROVED** [review]
Code looks good.

**Review by dolcalmi — CHANGES_REQUESTED** [review]
this needs to have integration tests, is too important to deploy without them. or this `test/integration/core/lock.spec.ts` covers the changes?

**Comment by vindard** [comment]
> this needs to have integration tests, is too important to deploy without them. or this `test/integration/core/lock.spec.ts` covers the changes?

New method is just a "safe" wrapper on `lockExtendOrThrow` which is tested in `test/integration/core/lock.spec.ts`. It also gets called as part of other methods in various places in the integrations tests so I was thinking explicit testing of the wrapping may not be needed.

**Review by dolcalmi — DISMISSED** [review]

**Review by dolcalmi — APPROVED** [review]

**Review by bodymindarts — APPROVED** [review]

**Pull request merged**
