### PR TITLE
chore: make it easier to understand the diff of a .graphql

### PR DESCRIPTION
**Pull request by nicolasburtey**
by computing another generated file which is lexicographic based
to remove the non deterministic aspect of the .graphql file creation

still keeping the standard schema.graphql as this is the one
that make most sense for an API user

### CODE REVIEW

**Comment by bodymindarts** [comment]
Haven’t looked at the diff but just a small comment. This does not qualify as a feature on the sense of semantic versioning. IMO it’s a chore or improvement.

**Comment by nicolasburtey** [comment]
> Haven’t looked at the diff but just a small comment. This does not qualify as a feature on the sense of semantic versioning. IMO it’s a chore or improvement.
> […](#)
> Sent from my iPhone
> On 4. Dec 2021, at 15:26, nicolasburtey ***@***.***> wrote: ﻿ @nicolasburtey requested your review on: #782 feat: make it easier to understand the diff of a .graphql. — You are receiving this because your review was requested. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

fixed

**Comment by samerbuna** [comment]
This SDL looks much better. I'd say let's just use it for the main schema files and not generate a different file.

**Review by bodymindarts — APPROVED** [review]
Just as a reminder we need to add a failing condition to the GitHub action integration test that fails if there is a diff post run.

**Review by dolcalmi — APPROVED** [review]
I am approving but I agree with @samerbuna.

**Comment by nicolasburtey** [comment]
updated with your reco @samerbuna @dolcalmi

**Review by samerbuna — APPROVED** [review]

**Pull request merged**
