### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by krtk6160**

### CODE REVIEW

**Review by nicolasburtey — COMMENTED** [review]
I think galoy-mobile might be a where this is most needed at first

**Comment by krtk6160** [comment]
> I think galoy-mobile might be a where this is most needed at first

Done [here](https://github.com/GaloyMoney/galoy-mobile/commit/8aed37a0f627d4a4aac569bd8bf31c0234f05173)

**Comment by dolcalmi** [comment]
> > I think galoy-mobile might be a where this is most needed at first
> 
> Done [here](https://github.com/GaloyMoney/galoy-mobile/commit/8aed37a0f627d4a4aac569bd8bf31c0234f05173)

so can we close this PR?

**Comment by nicolasburtey** [comment]
> > > I think galoy-mobile might be a where this is most needed at first
> > 
> > 
> > Done [here](https://github.com/GaloyMoney/galoy-mobile/commit/8aed37a0f627d4a4aac569bd8bf31c0234f05173)
> 
> so can we close this PR?

yes let's close it for now

**Pull request closed without merging**
