### PR TITLE
add types, payload, and mutation for UserQuizQuestions 

### PR DESCRIPTION
**Pull request by twshelton**
updates for new GraphQL schema

### CODE REVIEW

**Comment by bodymindarts** [comment]
`make check-code` is failing. I think you need to setup your editor to run `prettier` on save to avoid this being an issue.

Also we are trying to keep a consistent commit style - `C`apitalize the first word and rebase instead of having `Merge branch 'main' into ...` commits. A consistent commit history is easier to parse.

https://github.com/GaloyMoney/galoy/blob/main/DEV.md#contributing

**Comment by twshelton** [comment]
I was able to add eslint and prettier to editor over the weekend and have everything working.  I simply forgot to push the latest change to allow `check-code` to pass.  That portion should be good now.

As for the consistent commit history, what is the preferred workflow when merging upstream commits?  I have been using `git pull upstream main`.  Are you suggesting I use rebase instead?  And by `capitalize first word` do you mean the commit message? 

I'll get my workflow updated to meet these requirements.

**Comment by bodymindarts** [comment]
> I have been using `git pull upstream main`
I typically do:
```
git checkout main && git pull
git checkout <branch>
git rebase -i main
(... sort out merge conflicts...)
git push -f
```
>  And by capitalize first word do you mean the commit message?

Yes I'm talking about the commit message. If you scroll right to the bottom of the page (heading [#contributing](https://github.com/GaloyMoney/galoy/blob/main/DEV.md#contributing)) you will see links to 2 articles that can help you with commit style.

**Comment by samerbuna** [comment]
Continued in #549

**Pull request closed without merging**
