### PR TITLE
upgrade last mongodb version docker-compose

### PR DESCRIPTION
**Pull request by nicolasburtey**
(last version for the v4 branch)

### CODE REVIEW

**Comment by bodymindarts** [comment]
Have you verified this is the same container as the chart we are running on prod?

**Comment by nicolasburtey** [comment]
> Have you verified this is the same container as the chart we are running on prod?

nope. will do.

**Comment by nicolasburtey** [comment]
I guess it was already up to date from bitnami?

https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml#L102

**Comment by nicolasburtey** [comment]
actually we may not have the last version of the charts. 

I have hard time finding the mapping charts --> mongodb version mapping

**Review by bodymindarts — APPROVED** [review]

**Comment by krtk6160** [comment]
@nicolasburtey  [This PR](https://github.com/GaloyMoney/charts/pull/189) will upgrade our mongodb chart to latest so that we use the latest mongodb as well

**Review by krtk6160 — APPROVED** [review]

**Pull request merged**
