### PR TITLE
fix invoiceUser not existant issue

### PR DESCRIPTION
**Pull request by nicolasburtey**
this is related to https://github.com/GaloyMoney/lnpage/issues/57

### CODE REVIEW

**Comment by nicolasburtey** [comment]
@samerbuna I have to a `(invoice as GetInvoiceResult)` because I checked above that invoice should exist `if (!invoice)` so I'm not sure why this check is necessary. would love your insights on it.

**Comment by samerbuna** [comment]
> @samerbuna I have to a `(invoice as GetInvoiceResult)` because I checked above that invoice should exist `if (!invoice)` so I'm not sure why this check is necessary. would love your insights on it.

It's a bit annoying but because the `invoice` variable is used in an async function after, TypeScript strictly cannot guarantee that the value of `invoice` has not changed before the async function gets executed. This is why using `const` instead of `let` is preferable since that makes that guarantee, basically. You can wrap the invoice getting logic in a function to make it possible to use `const` in this particular case.

**Comment by nicolasburtey** [comment]
@samerbuna but I can't have a const because I'm wrapping up the call in a `try` `catch`?

**Comment by samerbuna** [comment]
> @samerbuna but I can't have a const because I'm wrapping up the call in a `try` `catch`?

Right, that's why you'll need to wrap that whole block in a function that returns `invoice | undefined`

**Pull request merged**
