### PR TITLE
chore: get back to mongo 4.4 on docker-compose

### PR DESCRIPTION
**Pull request by nicolasburtey**
on mongo 5 I get this error on M1:

```
galoy-mongodb-1  |
galoy-mongodb-1  | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
galoy-mongodb-1  |   see https://jira.mongodb.org/browse/SERVER-54407
galoy-mongodb-1  |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
galoy-mongodb-1  |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
galoy-mongodb-1  |
```

not sure if there are easy ways to solve this. haven't found any quickly

### CODE REVIEW

**Comment by dolcalmi** [comment]
what version is used in charts/prod?

**Comment by nicolasburtey** [comment]
> what version is used in charts/prod?

5 I think 

@krtk6160?

**Comment by dolcalmi** [comment]
@nicolasburtey  I cant test but maybe you can add this flag in docker compose file
```
- MONGO_INITDB_SKIP_AVX_CHECK=1
```

**Comment by nicolasburtey** [comment]
> MONGO_INITDB_SKIP_AVX_CHECK

do you have a link sharing how this flag could be useful? not finding anything on google

**Comment by krtk6160** [comment]
> > what version is used in charts/prod?
> 
> 5 I think
> 
> @krtk6160?

Yes

**Comment by krtk6160** [comment]
> 

How did you verify if it worked in linux? Do you have a processor without AVX support?

**Comment by krtk6160** [comment]
> @nicolasburtey I cant test but maybe you can add this flag in docker compose file
> 
> ```
> - MONGO_INITDB_SKIP_AVX_CHECK=1
> ```
> 
> it works in linux
> 
> ```
>   mongodb:
>     image: mongo:5.0.10
>     environment:
>       - MONGO_INITDB_DATABASE=galoy
>       - MONGO_INITDB_SKIP_AVX_CHECK=1
> ```

How did you verify if it worked in linux? Do you have a processor without AVX support?

**Comment by nicolasburtey** [comment]
> > @nicolasburtey I cant test but maybe you can add this flag in docker compose file
> > ```
> > - MONGO_INITDB_SKIP_AVX_CHECK=1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it works in linux
> > ```
> >   mongodb:
> >     image: mongo:5.0.10
> >     environment:
> >       - MONGO_INITDB_DATABASE=galoy
> >       - MONGO_INITDB_SKIP_AVX_CHECK=1
> > ```
> 
> How did you verify if it worked in linux? Do you have a processor without AVX support?

I would guess all revent processor nowadays have AVX... expect arm architecture, which are the chips new Mac book are based on

**Pull request closed without merging**
