### PR TITLE
chore(pay): add change username link

### PR DESCRIPTION
**Pull request by siddhart1o1**
image

### CODE REVIEW

**Comment by nicolasburtey** [comment]
- share / pin to home screen / change username not having the same width is not very pleasing from a UI standpoint
- I don't think it make sense to have Share as a primary button

**Comment by siddhart1o1** [comment]
> * share / pin to home screen / change username not having the same width is not very pleasing from a UI standpoint

updated

**Comment by siddhart1o1** [comment]
> * I don't think it make sense to have Share as a primary button

I will sync with Andre, it was in design.

**Comment by nicolasburtey** [comment]
I think it should be more a "Log out" option, that should be the same button whether it's just someone who has added a username, or someone who had sign in with the Oauth2 flow.

**Comment by siddhart1o1** [comment]
> I think it should be more a "Log out" option, that should be the same button whether it's just someone who has added a username, or someone who had sign in with the Oauth2 flow.

both are different options i think we can change the username of someone we want to pay, but maybe changing the username should not log us out ? But I can update this if you think it would make things more complex for users.

**Pull request closed without merging**
